### ISSUE TITLE
'high' errors do not cause grunt task to fail

### ISSUE THREAD

**Issue by dertseha** [kevinlacotaco/grunt-todos#9]
The [check](https://github.com/kevinlacotaco/grunt-todos/blob/73c799a118c9cd9821cf3be0672b80cc7f671fe8/tasks/todos.js#L118) for results.high does not work and will always resolve to false (no error reported).
`results` is not an object with this property, but an array containing objects that have an injected `priority` property.

**Comment by Bartvds** [comment]
It may be a little late news but I adopted this project on npm.

High-priority tasks fail the task now. See #10 for more info.

**Comment by dertseha** [comment]
Thank you, @Bartvds !
